### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ghost** [sproutVEVO/furima-35420#9]
### 自身のフリマアプリのURL
https://furima-35420.herokuapp.com/

### Basic認証のIDとパスワード
ID : admin / password : 1234

### 出品者用のメールアドレスとパスワード
mail : a@a / password : aaa111

### 購入者用のメールアドレスとパスワード
mail : b@b / password : bbb222

**Comment by snkw-works** [comment]
@sproutVEVO さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログアウト状態のユーザーは、URLを直接入力して商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらず「ログインページ」に遷移するよう修正しましょう**
現状、ログアウト状態のユーザーが、URLを直接入力するとトップページに遷移してしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ghost** [comment]
修正しました！

**Comment by keisukekodama** [comment]
@sproutVEVO さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/44963290/100499353-377ce500-31ac-11eb-87cc-2f4bfe1d4012.png)
